### ISSUE TITLE
Bug: Station does not generate cargo when train >> yard first

### ISSUE THREAD

**Issue by annoy-o-mus** [railwayco/railwayco#96]
There is this case where upon reaching the station, the train cargo list gets loaded, and then the player clicks to shift the cargo to the yard

And then click on the station cargo tab, and the tab will show nothing

It is likely due to the fact that the station yard cargo is still considered a station cargo rather than a separate category altogether and hence the station will not generate new cargo as long as there are yard cargo.

**Comment by wenenhoe** [comment]
Possible code snippet causing this bug

https://github.com/railwayco/railwayco/blob/2debd3db8c07b1bd76529e5abe77d67b30ed29e6/RailwayCo/Assets/Scripts/Unity/Main/LogicManager.cs#L156-L165

Count does not filter out whether it is yard or station cargo
